# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  name: rpi4
  description: Configuration files for my RPI4

  private: false
  archived: false

  has_issues: false
  has_projects: false
  has_wiki: false
  has_downloads: false

  default_branch: master
  delete_branch_on_merge: true

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
