version: "3.1"

services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: "host"
    volumes:
      - /var/media/plex:/config
      - /media/NFS:/media/NAS
    environment:
      PUID: "1000"
      PGID: "1000"
      VERSION: "public"
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    volumes:
      - /var/media/sonarr:/config
      - /media/NFS:/media/NAS
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Europe/London
    restart: unless-stopped
    networks:
      - default
      - gateway

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Europe/London
      AUTO_UPDATE: "false"
    volumes:
      - /var/media/jackett:/config
      - /var/media/torrents:/downloads
    ports:
      - 9117:9117
    #restart: unless-stopped
    networks:
      - default
      - gateway

  tautulli:
    image: ghcr.io/linuxserver/tautulli
    container_name: tautulli
    volumes:
      - /var/media/tautulli:/config
      - "/var/media/plex/Library/Application Support/Plex Media Server/Logs:/logs"
    environment:
      DOCKER_MODS: "" # Forces cURL to be installed so that tautulli2trakt.sh can run
      PUID: "1000"
      PGID: "1000"
      TZ: Europe/London
    restart: unless-stopped
    networks:
      - default
      - gateway

  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Europe/London
    volumes:
      - /var/media/transmission:/config
      - /var/media/torrents:/downloads
      - /var/media/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    #restart: unless-stopped
    networks:
      - default
      - gateway

networks:
  gateway:
    external: true
    name: gateway
