.DEFAULT_GOAL := help
.SILENT:

GREEN  := $(shell tput -Txterm setaf 2)
YELLOW := $(shell tput -Txterm setaf 3)
RESET  := $(shell tput -Txterm sgr0)

## Starts the containers
start:
	docker network create --driver=bridge --attachable --internal=false gateway || true
	docker-compose up -d --remove-orphans

## Stops the containers
stop:
	docker-compose down

## Stops the containers, updates the images and then starts the containers again
update:
	docker-compose pull
	docker-compose restart
	docker image prune -a -f

## Prints this help
help:
	@echo "\nUsage: make ${YELLOW}<target>${RESET}\n\nThe following targets are available:\n";
	@awk -v skip=1 \
		'/^##/ { sub(/^[#[:blank:]]*/, "", $$0); doc_h=$$0; doc=""; skip=0; next } \
		 skip  { next } \
		 /^#/  { doc=doc "\n" substr($$0, 2); next } \
		 /:/   { sub(/:.*/, "", $$0); printf "\033[34m%-30s\033[0m\033[1m%s\033[0m %s\n", $$0, doc_h, doc; skip=1 }' \
		$(MAKEFILE_LIST)
